/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Campaign = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'endings' : IDL.Vec(IDL.Text),
  'chapters' : IDL.Vec(IDL.Text),
});
export const PlayerProgress = IDL.Record({
  'currentCampaign' : IDL.Text,
  'reachedEndings' : IDL.Vec(IDL.Text),
  'choices' : IDL.Vec(IDL.Text),
  'currentChapter' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
  'getAllPlayerProgress' : IDL.Func([], [IDL.Vec(PlayerProgress)], ['query']),
  'getCampaign' : IDL.Func([IDL.Text], [Campaign], ['query']),
  'getProgress' : IDL.Func([], [PlayerProgress], ['query']),
  'getReachedEndings' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'isProgressSaved' : IDL.Func([], [IDL.Bool], ['query']),
  'saveProgress' : IDL.Func([PlayerProgress], [], []),
  'updateProgress' : IDL.Func([PlayerProgress], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Campaign = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'endings' : IDL.Vec(IDL.Text),
    'chapters' : IDL.Vec(IDL.Text),
  });
  const PlayerProgress = IDL.Record({
    'currentCampaign' : IDL.Text,
    'reachedEndings' : IDL.Vec(IDL.Text),
    'choices' : IDL.Vec(IDL.Text),
    'currentChapter' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllCampaigns' : IDL.Func([], [IDL.Vec(Campaign)], ['query']),
    'getAllPlayerProgress' : IDL.Func([], [IDL.Vec(PlayerProgress)], ['query']),
    'getCampaign' : IDL.Func([IDL.Text], [Campaign], ['query']),
    'getProgress' : IDL.Func([], [PlayerProgress], ['query']),
    'getReachedEndings' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'isProgressSaved' : IDL.Func([], [IDL.Bool], ['query']),
    'saveProgress' : IDL.Func([PlayerProgress], [], []),
    'updateProgress' : IDL.Func([PlayerProgress], [], []),
  });
};

export const init = ({ IDL }) => { return []; };